name: GitHub CI

on:
    workflow_dispatch:

jobs:
  windowsBuild:
    name: Windows Build
    runs-on: windows-latest
    env:
      LLVM_VERSION: 19.1.7
      LLVM_MAJOR_VERSION: 19

    strategy:
      fail-fast: false
      matrix:
        CRT:
        - libcmt

        TARGET_CPU:
        - amd64

        CONFIGURATION:
        - Release

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install
      shell: cmd
      run: |
        call %GITHUB_WORKSPACE%\set-env.bat msvc17 ${{matrix.CRT}} ${{matrix.TARGET_CPU}} ${{matrix.CONFIGURATION}}
        call %GITHUB_WORKSPACE%\install.bat

    - name: Build and test
      id: BUILD
      shell: cmd
      run: |
        call %GITHUB_WORKSPACE%\set-env.bat msvc17 ${{matrix.CRT}} ${{matrix.TARGET_CPU}} ${{matrix.CONFIGURATION}}
        call %GITHUB_WORKSPACE%\build.bat
        echo ::set-output name=DEPLOY_FILE::%DEPLOY_FILE%
        set ARTIFACT_PATH=C:\a\win-llvm\win-llvm
        set ARTIFACT_PATH=%ARTIFACT_PATH%\%DEPLOY_FILE%
        echo ARTIFACT_PATH=%ARTIFACT_PATH% >> $env:GITHUB_ENV
        
    - uses: actions/upload-artifact@v4
      with:
        name: llvm-msvc
        path: ${{ env.ARTIFACT_PATH }}
